git setup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,41 @@
 #!/usr/bin/env bash
 
+info () {
+  printf "  [ \033[00;34m..\033[0m ] $1"
+}
+
+user () {
+  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+}
+
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+setup_gitconfig () {
+    if ! [ -f git/gitconfig.symlink ]
+    then
+    info 'setup gitconfig'
+
+    user ' - What is your github author name?'
+    read -e git_authorname
+    user ' - What is your github author email?'
+    read -e git_authoremail
+
+    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g"  git/gitconfig > git/gitconfig.symlink
+
+    success 'gitconfig'
+  fi
+}
+
+setup_gitconfig
+
 set -e
 
 CONFIG="install.conf.yaml"
